CREATE SCHEMA IF NOT EXISTS discuz;

CREATE TABLE IF NOT EXISTS discuz.common_member_profile (
    uid int4 NOT NULL,
    realname varchar(255) DEFAULT ''::character varying NOT NULL,
    gender int2 DEFAULT '0'::smallint NOT NULL,
    birthyear int4 DEFAULT 0 NOT NULL,
    birthmonth int2 DEFAULT '0'::smallint NOT NULL,
    birthday int2 DEFAULT '0'::smallint NOT NULL,
    constellation varchar(255) DEFAULT ''::character varying NOT NULL,
    zodiac varchar(255) DEFAULT ''::character varying NOT NULL,
    telephone varchar(255) DEFAULT ''::character varying NOT NULL,
    mobile varchar(255) DEFAULT ''::character varying NOT NULL,
    idcardtype varchar(255) DEFAULT ''::character varying NOT NULL,
    idcard varchar(255) DEFAULT ''::character varying NOT NULL,
    address varchar(255) DEFAULT ''::character varying NOT NULL,
    zipcode varchar(255) DEFAULT ''::character varying NOT NULL,
    nationality varchar(255) DEFAULT ''::character varying NOT NULL,
    birthcountry varchar(255) DEFAULT ''::character varying NOT NULL,
    birthprovince varchar(255) DEFAULT ''::character varying NOT NULL,
    birthcity varchar(255) DEFAULT ''::character varying NOT NULL,
    resideprovince varchar(255) DEFAULT ''::character varying NOT NULL,
    residecity varchar(255) DEFAULT ''::character varying NOT NULL,
    residedist varchar(20) DEFAULT ''::character varying NOT NULL,
    residecommunity varchar(255) DEFAULT ''::character varying NOT NULL,
    residesuite varchar(255) DEFAULT ''::character varying NOT NULL,
    graduateschool varchar(255) DEFAULT ''::character varying NOT NULL,
    company varchar(255) DEFAULT ''::character varying NOT NULL,
    education varchar(255) DEFAULT ''::character varying NOT NULL,
    occupation varchar(255) DEFAULT ''::character varying NOT NULL,
    "position" varchar(255) DEFAULT ''::character varying NOT NULL,
    revenue varchar(255) DEFAULT ''::character varying NOT NULL,
    affectivestatus varchar(255) DEFAULT ''::character varying NOT NULL,
    lookingfor varchar(255) DEFAULT ''::character varying NOT NULL,
    bloodtype varchar(255) DEFAULT ''::character varying NOT NULL,
    height varchar(255) DEFAULT ''::character varying NOT NULL,
    weight varchar(255) DEFAULT ''::character varying NOT NULL,
    alipay varchar(255) DEFAULT ''::character varying NOT NULL,
    icq varchar(255) DEFAULT ''::character varying NOT NULL,
    qq varchar(255) DEFAULT ''::character varying NOT NULL,
    yahoo varchar(255) DEFAULT ''::character varying NOT NULL,
    msn varchar(255) DEFAULT ''::character varying NOT NULL,
    taobao varchar(255) DEFAULT ''::character varying NOT NULL,
    site varchar(255) DEFAULT ''::character varying NOT NULL,
    bio text NOT NULL,
    interest text NOT NULL,
    field1 text NOT NULL,
    field2 text NOT NULL,
    field3 text NOT NULL,
    field4 text NOT NULL,
    field5 text NOT NULL,
    field6 text NOT NULL,
    field7 text NOT NULL,
    field8 text NOT NULL,
    birthdist varchar(20) DEFAULT ''::character varying NOT NULL,
    birthcommunity varchar(255) DEFAULT ''::character varying NOT NULL,
    residecountry varchar(255) DEFAULT ''::character varying NOT NULL,
    CONSTRAINT idx_51236_primary PRIMARY KEY (uid)
);
